import type {
  CaseChecklistItem,
  CaseRecord,
  ClientRecord,
  ContactRecord,
  OrderRecord,
  PartyRecord,
  ProductRecord,
  ProjectRecord,
  TaskRecord,
  UserRecord,
} from './records';
import { ORG_KUNZ_ID } from '@/lib/org-profiles/profiles';

const ORG = ORG_KUNZ_ID;

export const KUNZ_USERS: UserRecord[] = [
  {
    id: 'usr_kunz_owner',
    name: 'Klaus Ostermann',
    email: 'ostermann@bestattung-kunz.at',
    role: 'Admin',
    status: 'Active',
    team: 'Leitung',
  },
  {
    id: 'usr_kunz_member1',
    name: 'Andrea Schober',
    email: 'schober@bestattung-kunz.at',
    role: 'Manager',
    status: 'Active',
    team: 'Sterbefälle',
  },
  {
    id: 'usr_kunz_member2',
    name: 'Markus Weber',
    email: 'weber@bestattung-kunz.at',
    role: 'Member',
    status: 'Active',
    team: 'Aufbahrung',
  },
];

export const KUNZ_CLIENTS: ClientRecord[] = [
  {
    id: 'cli_kunz_1',
    orgId: ORG,
    name: 'Friedhofsverwaltung Pitten',
    type: 'company',
    industry: 'Friedhof',
    status: 'active',
    email: 'friedhof@pitten.gv.at',
    phone: '+43 2627 82335',
    website: '',
    country: 'AT',
    city: 'Pitten',
    tags: ['friedhof', 'behörde'],
    notes: 'Friedhofsgebühren und Grabstellen',
    annualRevenue: '',
    contractStart: '',
    contractEnd: '',
    accountManager: 'Klaus Ostermann',
    createdAt: '2024-01-10',
  },
  {
    id: 'cli_kunz_2',
    orgId: ORG,
    name: 'Steinhauer Pichler',
    type: 'company',
    industry: 'Steinmetz',
    status: 'active',
    email: 'office@steinmetz-pichler.at',
    phone: '+43 2622 232 66',
    website: '',
    country: 'AT',
    city: 'Wiener Neustadt',
    tags: ['lieferant', 'grabstein'],
    notes: 'Grabsteine und Grabeinfassungen',
    annualRevenue: '',
    contractStart: '',
    contractEnd: '',
    accountManager: 'Andrea Schober',
    createdAt: '2024-02-14',
  },
  {
    id: 'cli_kunz_3',
    orgId: ORG,
    name: 'Pfarrer Mag. Helmut König',
    type: 'individual',
    industry: 'Kirche',
    status: 'active',
    email: 'pfarre.pitten@dioezese.at',
    phone: '+43 2627 82210',
    website: '',
    country: 'AT',
    city: 'Pitten',
    tags: ['pfarrer', 'zeremonie'],
    notes: 'Seelsorge und kirchliche Zeremonien',
    annualRevenue: '',
    contractStart: '',
    contractEnd: '',
    accountManager: 'Markus Weber',
    createdAt: '2024-03-01',
  },
  {
    id: 'cli_kunz_4',
    orgId: ORG,
    name: 'Hermine Wallner',
    type: 'individual',
    industry: 'Vorsorge',
    status: 'active',
    email: 'h.wallner@aon.at',
    phone: '+43 664 123 4567',
    website: '',
    country: 'AT',
    city: 'Pitten',
    tags: ['vorsorge', 'kunde'],
    notes: 'Vorsorgevertrag',
    annualRevenue: '',
    contractStart: '2022-06-01',
    contractEnd: '',
    accountManager: 'Klaus Ostermann',
    createdAt: '2022-06-01',
  },
  {
    id: 'cli_kunz_5',
    orgId: ORG,
    name: 'Blumen Eder',
    type: 'company',
    industry: 'Floristik',
    status: 'active',
    email: 'bestellung@blumen-eder.at',
    phone: '+43 2627 484 10',
    website: '',
    country: 'AT',
    city: 'Pitten',
    tags: ['lieferant', 'floristik'],
    notes: 'Trauerfloristik',
    annualRevenue: '',
    contractStart: '',
    contractEnd: '',
    accountManager: 'Andrea Schober',
    createdAt: '2024-04-20',
  },
];

export const KUNZ_CONTACTS: ContactRecord[] = [
  {
    id: 'cnt_kunz_1',
    orgId: ORG,
    firstName: 'Andreas',
    lastName: 'Schober',
    email: 'schober@bestattung-kunz.at',
    phone: '+43 2627 82336',
    role: 'Manager',
    clientId: 'cli_kunz_1',
    clientName: 'Friedhofsverwaltung Pitten',
    status: 'Active',
    source: 'Manual',
    tags: ['leitung'],
    notes: 'Verantwortlich für Trauerfallsplanung.',
    createdAt: '2024-01-12',
  },
  {
    id: 'cnt_kunz_2',
    orgId: ORG,
    firstName: 'Markus',
    lastName: 'Weber',
    email: 'weber@bestattung-kunz.at',
    phone: '+43 2627 82337',
    role: 'Mitarbeiter',
    clientId: 'cli_kunz_4',
    clientName: 'Hermine Wallner',
    status: 'Active',
    source: 'Referral',
    tags: ['fallbearbeitung'],
    notes: 'Ansprechpartnerin für Vorsorgethemen in der Pitten Filiale.',
    createdAt: '2024-02-01',
  },
  {
    id: 'cnt_kunz_3',
    orgId: ORG,
    firstName: 'Lara',
    lastName: 'Huber',
    email: 'lara.huber@bestattung-kunz.at',
    phone: '+43 2622 232 67',
    role: 'Sargtransport',
    clientId: 'cli_kunz_2',
    clientName: 'Steinhauer Pichler',
    status: 'Active',
    source: 'Referral',
    tags: ['lieferant'],
    notes: 'Koordination für Grabsteine und Beisetzungszubehör.',
    createdAt: '2024-03-05',
  },
  {
    id: 'cnt_kunz_4',
    orgId: ORG,
    firstName: 'Magdalena',
    lastName: 'König',
    email: 'pfarre.pitten@dioezese.at',
    phone: '+43 2627 82210',
    role: 'Seelsorge',
    clientId: 'cli_kunz_3',
    clientName: 'Pfarrer Mag. Helmut König',
    status: 'Active',
    source: 'Manual',
    tags: ['zeremonie'],
    notes: 'Terminabstimmung für Trauerfeiern und liturgische Unterstützung.',
    createdAt: '2024-03-20',
  },
];

export const KUNZ_PRODUCTS: ProductRecord[] = [
  {
    id: 'prd_kunz_1',
    orgId: ORG,
    sku: 'BK-SVC-001',
    name: 'Überführung im Inland',
    category: 'Leistungen',
    status: 'Active',
    currency: 'EUR',
    price: '450',
    stock: 0,
    unit: 'pauschal',
  },
  {
    id: 'prd_kunz_2',
    orgId: ORG,
    sku: 'BK-SVC-002',
    name: 'Aufbahrung und Trauerfeier',
    category: 'Leistungen',
    status: 'Active',
    currency: 'EUR',
    price: '680',
    stock: 0,
    unit: 'pauschal',
  },
  {
    id: 'prd_kunz_3',
    orgId: ORG,
    sku: 'BK-PRD-001',
    name: 'Sarg Eiche massiv',
    category: 'Särge',
    status: 'Active',
    currency: 'EUR',
    price: '2400',
    stock: 4,
    unit: 'Stück',
  },
  {
    id: 'prd_kunz_4',
    orgId: ORG,
    sku: 'BK-PRD-002',
    name: 'Urne Keramik',
    category: 'Urnen',
    status: 'Active',
    currency: 'EUR',
    price: '380',
    stock: 12,
    unit: 'Stück',
  },
  {
    id: 'prd_kunz_5',
    orgId: ORG,
    sku: 'BK-SVC-003',
    name: 'Partezettel (100 Stk.)',
    category: 'Druck',
    status: 'Active',
    currency: 'EUR',
    price: '195',
    stock: 0,
    unit: 'pauschal',
  },
];

export const KUNZ_CASES: CaseRecord[] = [
  {
    id: 'case_kunz_1',
    orgId: ORG,
    caseNumber: 'KUNZ-2026-0042',
    title: 'Trauerfall Wallner Friedrich',
    type: 'Erdbestattung',
    stage: 'Durchführung',
    priority: 'High',
    clientId: 'cli_kunz_4',
    clientName: 'Hermine Wallner',
    assignee: 'Andrea Schober',
    openedAt: '2026-05-12',
    dueAt: '2026-05-28',
    slaStatus: 'ok',
    summary:
      'Erdbestattung mit Aufbahrung in der Aufbahrungshalle Pitten. Trauerfeier Pfarrkirche Pitten.',
    deceasedName: 'Friedrich Wallner',
    dateOfDeath: '2026-05-10',
    arrangementType: 'Erdbestattung',
    burialSite: 'Friedhof Pitten',
    locationSite: 'Filialbetrieb Pitten',
  },
  {
    id: 'case_kunz_2',
    orgId: ORG,
    caseNumber: 'KUNZ-2026-0038',
    title: 'Trauerfall Huber Maria',
    type: 'Feuerbestattung',
    stage: 'Planung',
    priority: 'Normal',
    clientId: 'cli_kunz_3',
    clientName: 'Pfarrer Mag. Helmut König',
    assignee: 'Markus Weber',
    openedAt: '2026-05-08',
    dueAt: '2026-05-22',
    slaStatus: 'ok',
    summary: 'Feuerbestattung mit Urnenbeisetzung Neunkirchen. Partezettel in Druck.',
    deceasedName: 'Maria Huber',
    dateOfDeath: '2026-05-07',
    arrangementType: 'Feuerbestattung',
    burialSite: 'Friedhof Neunkirchen',
    locationSite: 'Filialbetrieb Neunkirchen',
  },
  {
    id: 'case_kunz_3',
    orgId: ORG,
    caseNumber: 'KUNZ-2026-0031',
    title: 'Vorsorge Wallner — Ergänzung',
    type: 'Vorsorge',
    stage: 'Aufnahme',
    priority: 'Low',
    clientId: 'cli_kunz_4',
    clientName: 'Hermine Wallner',
    assignee: 'Klaus Ostermann',
    openedAt: '2026-04-18',
    dueAt: '2026-06-30',
    slaStatus: 'ok',
    summary: 'Bestehender Vorsorgevertrag — Wunsch nach Urnenwahl und Musikwünschen.',
    arrangementType: 'Vorsorge',
    locationSite: 'Filialbetrieb Pitten',
  },
  {
    id: 'case_kunz_4',
    orgId: ORG,
    caseNumber: 'KUNZ-2026-0025',
    title: 'Trauerfall Gruber Johann',
    type: 'Erdbestattung',
    stage: 'Abgeschlossen',
    priority: 'Normal',
    clientId: 'cli_kunz_1',
    clientName: 'Friedhofsverwaltung Pitten',
    assignee: 'Andrea Schober',
    openedAt: '2026-03-02',
    dueAt: '2026-03-20',
    slaStatus: 'ok',
    summary: 'Abgeschlossen. Graböffnung und Beisetzung dokumentiert.',
    deceasedName: 'Johann Gruber',
    dateOfDeath: '2026-02-28',
    arrangementType: 'Erdbestattung',
    burialSite: 'Friedhof Pitten',
    locationSite: 'Filialbetrieb Pitten',
  },
];

export const KUNZ_CASE_CHECKLISTS: CaseChecklistItem[] = [
  {
    id: 'chk_kunz_1',
    caseId: 'case_kunz_1',
    label: 'Bestattungsauftrag digitalisiert',
    done: true,
    required: true,
  },
  {
    id: 'chk_kunz_2',
    caseId: 'case_kunz_1',
    label: 'Überführung dokumentiert',
    done: true,
    required: true,
  },
  {
    id: 'chk_kunz_3',
    caseId: 'case_kunz_1',
    label: 'Trauerfeier mit Pfarrer abgestimmt',
    done: false,
    required: true,
  },
  {
    id: 'chk_kunz_4',
    caseId: 'case_kunz_1',
    label: 'Friedhofsgebühren eingereicht',
    done: false,
    required: true,
  },
  {
    id: 'chk_kunz_5',
    caseId: 'case_kunz_2',
    label: 'Urne ausgewählt',
    done: true,
    required: true,
  },
  {
    id: 'chk_kunz_6',
    caseId: 'case_kunz_2',
    label: 'Krematoriums-Termin reserviert',
    done: false,
    required: true,
  },
];

export const KUNZ_PARTIES: PartyRecord[] = [
  {
    id: 'pty_kunz_1',
    caseId: 'case_kunz_1',
    name: 'Hermine Wallner',
    role: 'Auftraggeberin',
    email: 'h.wallner@aon.at',
  },
  {
    id: 'pty_kunz_2',
    caseId: 'case_kunz_1',
    name: 'Pfarrer Mag. Helmut König',
    role: 'Pfarrer',
    email: 'pfarre.pitten@dioezese.at',
  },
  {
    id: 'pty_kunz_3',
    caseId: 'case_kunz_2',
    name: 'Erika Huber',
    role: 'Auftraggeberin',
    email: 'erika.huber@example.at',
  },
];

export const KUNZ_PROJECTS: ProjectRecord[] = [
  {
    id: 'prj_kunz_1',
    orgId: ORG,
    name: 'Trauerfall Wallner Friedrich',
    clientName: 'Hermine Wallner',
    status: 'Active',
    manager: 'Andrea Schober',
    startDate: '2026-05-12',
    endDate: '2026-05-28',
    budget: '4850',
    completion: 72,
  },
];

export const KUNZ_ORDERS: OrderRecord[] = [
  {
    id: 'ord_kunz_1',
    orgId: ORG,
    orderNumber: 'VK-2026-0188',
    clientId: 'cli_kunz_4',
    clientName: 'Hermine Wallner',
    status: 'Confirmed',
    total: '3530',
    orderDate: '2026-05-13',
    dueDate: '2026-05-25',
    owner: 'Andrea Schober',
    lineCount: 4,
  },
];

export const KUNZ_TASKS: TaskRecord[] = [
  {
    id: 'tsk_kunz_1',
    orgId: ORG,
    parentId: 'case_kunz_1',
    parentType: 'case',
    title: 'Partezettel Freigabe',
    assignee: 'Markus Weber',
    dueDate: '2026-05-18',
    status: 'Active',
  },
  {
    id: 'tsk_kunz_2',
    orgId: ORG,
    parentId: 'case_kunz_2',
    parentType: 'case',
    title: 'Blumen Eder — Trauerkranz',
    assignee: 'Andrea Schober',
    dueDate: '2026-05-20',
    status: 'Pending',
  },
];
