/**
 * Scans locales/de/*.json filenames and emits src/generated-namespaces.ts
 * + src/translations.ts (bundle map + lazy loaders) so namespace lists stay in sync.
 */
import { readdirSync, writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');
const LOCALES = join(ROOT, 'locales');
const SRC = join(ROOT, 'src');

const CORE = ['common', 'navigation', 'errors', 'validation', 'entities'];

const files = readdirSync(join(LOCALES, 'de'))
  .filter((f) => f.endsWith('.json') && !f.startsWith('_'))
  .map((f) => f.replace(/\.json$/, ''))
  .sort();

const all = files;
const core = CORE.filter((c) => all.includes(c));
const lazy = all.filter((n) => !core.includes(n));

const tsIdent = (s: string) => s.replace(/[^A-Za-z0-9]/g, '_');

function genNamespacesFile() {
  const body = `// AUTO-GENERATED by scripts/generate-namespaces.ts. Do not edit.

export type TranslationNamespace =
${all.map((n) => `  | '${n}'`).join('\n')};

export const ALL_NAMESPACES: TranslationNamespace[] = [
${all.map((n) => `  '${n}',`).join('\n')}
];

export const CORE_NAMESPACES: TranslationNamespace[] = [
${core.map((n) => `  '${n}',`).join('\n')}
];

export const LAZY_NAMESPACES: TranslationNamespace[] = [
${lazy.map((n) => `  '${n}',`).join('\n')}
];
`;
  writeFileSync(join(SRC, 'generated-namespaces.ts'), body);
}

function genTranslationsFile() {
  const eagerImports = core
    .flatMap((n) => [
      `import en_${tsIdent(n)} from '../locales/en/${n}.json';`,
      `import de_${tsIdent(n)} from '../locales/de/${n}.json';`,
    ])
    .join('\n');

  const lazyMap = (lang: 'en' | 'de') =>
    lazy.map((n) => `    '${n}': () => import('../locales/${lang}/${n}.json').then((m) => m.default),`).join('\n');

  const body = `// AUTO-GENERATED by scripts/generate-namespaces.ts. Do not edit.
import type { LanguageCode } from './types';
import type { TranslationNamespace } from './generated-namespaces';

${eagerImports}

export const coreTranslations: Record<LanguageCode, Record<string, Record<string, unknown>>> = {
  en: {
${core.map((n) => `    ${n}: en_${tsIdent(n)} as Record<string, unknown>,`).join('\n')}
  },
  de: {
${core.map((n) => `    ${n}: de_${tsIdent(n)} as Record<string, unknown>,`).join('\n')}
  },
};

type LazyLoader = () => Promise<Record<string, unknown>>;
const lazyLoaders: Record<LanguageCode, Record<string, LazyLoader>> = {
  en: {
${lazyMap('en')}
  },
  de: {
${lazyMap('de')}
  },
};

export async function loadNamespace(
  language: LanguageCode,
  namespace: TranslationNamespace,
): Promise<Record<string, unknown>> {
  const core = coreTranslations[language]?.[namespace];
  if (core) return core;
  const loader = lazyLoaders[language]?.[namespace];
  if (!loader) return {};
  try {
    return await loader();
  } catch (error) {
    console.warn(\`[i18n] Failed to load \${language}/\${namespace}\`, error);
    return {};
  }
}

export async function loadNamespaces(
  language: LanguageCode,
  namespaces: TranslationNamespace[],
): Promise<Record<string, Record<string, unknown>>> {
  const out: Record<string, Record<string, unknown>> = {};
  await Promise.all(
    namespaces.map(async (ns) => {
      out[ns] = await loadNamespace(language, ns);
    }),
  );
  return out;
}

export { CORE_NAMESPACES, LAZY_NAMESPACES, ALL_NAMESPACES } from './generated-namespaces';
export type { TranslationNamespace } from './generated-namespaces';
`;
  writeFileSync(join(SRC, 'translations.ts'), body);
}

genNamespacesFile();
genTranslationsFile();
console.log(`Generated ${all.length} namespaces (${core.length} core, ${lazy.length} lazy)`);
