// AUTO-GENERATED by scripts/generate-namespaces.ts. Do not edit.

export type TranslationNamespace =
  | 'addresses'
  | 'admin'
  | 'ai_usage'
  | 'auth'
  | 'bills'
  | 'calendar'
  | 'calendarV2'
  | 'catalog'
  | 'changelog'
  | 'clients'
  | 'common'
  | 'contacts'
  | 'customers'
  | 'dashboard'
  | 'doc_processing'
  | 'documents'
  | 'email'
  | 'entities'
  | 'errors'
  | 'estates'
  | 'fahrtenbuch'
  | 'forms'
  | 'funeral_cases'
  | 'funeral_cases_v2'
  | 'group-chat'
  | 'holidays'
  | 'immobilien'
  | 'knowledge'
  | 'leads'
  | 'modifier'
  | 'modules'
  | 'navigation'
  | 'profile'
  | 'projects'
  | 'property_management'
  | 'purchasing'
  | 'sales'
  | 'scheduler'
  | 'settings'
  | 'staff'
  | 'storage'
  | 'superadmin'
  | 'support'
  | 'template_gen'
  | 'time_tracking'
  | 'validation'
  | 'vendors';

export const ALL_NAMESPACES: TranslationNamespace[] = [
  'addresses',
  'admin',
  'ai_usage',
  'auth',
  'bills',
  'calendar',
  'calendarV2',
  'catalog',
  'changelog',
  'clients',
  'common',
  'contacts',
  'customers',
  'dashboard',
  'doc_processing',
  'documents',
  'email',
  'entities',
  'errors',
  'estates',
  'fahrtenbuch',
  'forms',
  'funeral_cases',
  'funeral_cases_v2',
  'group-chat',
  'holidays',
  'immobilien',
  'knowledge',
  'leads',
  'modifier',
  'modules',
  'navigation',
  'profile',
  'projects',
  'property_management',
  'purchasing',
  'sales',
  'scheduler',
  'settings',
  'staff',
  'storage',
  'superadmin',
  'support',
  'template_gen',
  'time_tracking',
  'validation',
  'vendors',
];

export const CORE_NAMESPACES: TranslationNamespace[] = [
  'common',
  'navigation',
  'errors',
  'validation',
  'entities',
];

export const LAZY_NAMESPACES: TranslationNamespace[] = [
  'addresses',
  'admin',
  'ai_usage',
  'auth',
  'bills',
  'calendar',
  'calendarV2',
  'catalog',
  'changelog',
  'clients',
  'contacts',
  'customers',
  'dashboard',
  'doc_processing',
  'documents',
  'email',
  'estates',
  'fahrtenbuch',
  'forms',
  'funeral_cases',
  'funeral_cases_v2',
  'group-chat',
  'holidays',
  'immobilien',
  'knowledge',
  'leads',
  'modifier',
  'modules',
  'profile',
  'projects',
  'property_management',
  'purchasing',
  'sales',
  'scheduler',
  'settings',
  'staff',
  'storage',
  'superadmin',
  'support',
  'template_gen',
  'time_tracking',
  'vendors',
];
