// AUTO-GENERATED by scripts/generate-namespaces.ts. Do not edit.
import type { LanguageCode } from './types';
import type { TranslationNamespace } from './generated-namespaces';

import en_common from '../locales/en/common.json';
import de_common from '../locales/de/common.json';
import en_navigation from '../locales/en/navigation.json';
import de_navigation from '../locales/de/navigation.json';
import en_errors from '../locales/en/errors.json';
import de_errors from '../locales/de/errors.json';
import en_validation from '../locales/en/validation.json';
import de_validation from '../locales/de/validation.json';
import en_entities from '../locales/en/entities.json';
import de_entities from '../locales/de/entities.json';

export const coreTranslations: Record<LanguageCode, Record<string, Record<string, unknown>>> = {
  en: {
    common: en_common as Record<string, unknown>,
    navigation: en_navigation as Record<string, unknown>,
    errors: en_errors as Record<string, unknown>,
    validation: en_validation as Record<string, unknown>,
    entities: en_entities as Record<string, unknown>,
  },
  de: {
    common: de_common as Record<string, unknown>,
    navigation: de_navigation as Record<string, unknown>,
    errors: de_errors as Record<string, unknown>,
    validation: de_validation as Record<string, unknown>,
    entities: de_entities as Record<string, unknown>,
  },
};

type LazyLoader = () => Promise<Record<string, unknown>>;
const lazyLoaders: Record<LanguageCode, Record<string, LazyLoader>> = {
  en: {
    addresses: () => import('../locales/en/addresses.json').then((m) => m.default),
    admin: () => import('../locales/en/admin.json').then((m) => m.default),
    ai_usage: () => import('../locales/en/ai_usage.json').then((m) => m.default),
    auth: () => import('../locales/en/auth.json').then((m) => m.default),
    bills: () => import('../locales/en/bills.json').then((m) => m.default),
    calendar: () => import('../locales/en/calendar.json').then((m) => m.default),
    calendarV2: () => import('../locales/en/calendarV2.json').then((m) => m.default),
    catalog: () => import('../locales/en/catalog.json').then((m) => m.default),
    clients: () => import('../locales/en/clients.json').then((m) => m.default),
    contacts: () => import('../locales/en/contacts.json').then((m) => m.default),
    customers: () => import('../locales/en/customers.json').then((m) => m.default),
    dashboard: () => import('../locales/en/dashboard.json').then((m) => m.default),
    doc_processing: () => import('../locales/en/doc_processing.json').then((m) => m.default),
    documents: () => import('../locales/en/documents.json').then((m) => m.default),
    email: () => import('../locales/en/email.json').then((m) => m.default),
    estates: () => import('../locales/en/estates.json').then((m) => m.default),
    fahrtenbuch: () => import('../locales/en/fahrtenbuch.json').then((m) => m.default),
    forms: () => import('../locales/en/forms.json').then((m) => m.default),
    funeral_cases: () => import('../locales/en/funeral_cases.json').then((m) => m.default),
    funeral_cases_v2: () => import('../locales/en/funeral_cases_v2.json').then((m) => m.default),
    'group-chat': () => import('../locales/en/group-chat.json').then((m) => m.default),
    holidays: () => import('../locales/en/holidays.json').then((m) => m.default),
    immobilien: () => import('../locales/en/immobilien.json').then((m) => m.default),
    knowledge: () => import('../locales/en/knowledge.json').then((m) => m.default),
    leads: () => import('../locales/en/leads.json').then((m) => m.default),
    modifier: () => import('../locales/en/modifier.json').then((m) => m.default),
    modules: () => import('../locales/en/modules.json').then((m) => m.default),
    profile: () => import('../locales/en/profile.json').then((m) => m.default),
    projects: () => import('../locales/en/projects.json').then((m) => m.default),
    property_management: () =>
      import('../locales/en/property_management.json').then((m) => m.default),
    purchasing: () => import('../locales/en/purchasing.json').then((m) => m.default),
    sales: () => import('../locales/en/sales.json').then((m) => m.default),
    scheduler: () => import('../locales/en/scheduler.json').then((m) => m.default),
    settings: () => import('../locales/en/settings.json').then((m) => m.default),
    staff: () => import('../locales/en/staff.json').then((m) => m.default),
    storage: () => import('../locales/en/storage.json').then((m) => m.default),
    superadmin: () => import('../locales/en/superadmin.json').then((m) => m.default),
    support: () => import('../locales/en/support.json').then((m) => m.default),
    template_gen: () => import('../locales/en/template_gen.json').then((m) => m.default),
    time_tracking: () => import('../locales/en/time_tracking.json').then((m) => m.default),
    vendors: () => import('../locales/en/vendors.json').then((m) => m.default),
  },
  de: {
    addresses: () => import('../locales/de/addresses.json').then((m) => m.default),
    admin: () => import('../locales/de/admin.json').then((m) => m.default),
    ai_usage: () => import('../locales/de/ai_usage.json').then((m) => m.default),
    auth: () => import('../locales/de/auth.json').then((m) => m.default),
    bills: () => import('../locales/de/bills.json').then((m) => m.default),
    calendar: () => import('../locales/de/calendar.json').then((m) => m.default),
    calendarV2: () => import('../locales/de/calendarV2.json').then((m) => m.default),
    catalog: () => import('../locales/de/catalog.json').then((m) => m.default),
    clients: () => import('../locales/de/clients.json').then((m) => m.default),
    contacts: () => import('../locales/de/contacts.json').then((m) => m.default),
    customers: () => import('../locales/de/customers.json').then((m) => m.default),
    dashboard: () => import('../locales/de/dashboard.json').then((m) => m.default),
    doc_processing: () => import('../locales/de/doc_processing.json').then((m) => m.default),
    documents: () => import('../locales/de/documents.json').then((m) => m.default),
    email: () => import('../locales/de/email.json').then((m) => m.default),
    estates: () => import('../locales/de/estates.json').then((m) => m.default),
    fahrtenbuch: () => import('../locales/de/fahrtenbuch.json').then((m) => m.default),
    forms: () => import('../locales/de/forms.json').then((m) => m.default),
    funeral_cases: () => import('../locales/de/funeral_cases.json').then((m) => m.default),
    funeral_cases_v2: () => import('../locales/de/funeral_cases_v2.json').then((m) => m.default),
    'group-chat': () => import('../locales/de/group-chat.json').then((m) => m.default),
    holidays: () => import('../locales/de/holidays.json').then((m) => m.default),
    immobilien: () => import('../locales/de/immobilien.json').then((m) => m.default),
    knowledge: () => import('../locales/de/knowledge.json').then((m) => m.default),
    leads: () => import('../locales/de/leads.json').then((m) => m.default),
    modifier: () => import('../locales/de/modifier.json').then((m) => m.default),
    modules: () => import('../locales/de/modules.json').then((m) => m.default),
    profile: () => import('../locales/de/profile.json').then((m) => m.default),
    projects: () => import('../locales/de/projects.json').then((m) => m.default),
    property_management: () =>
      import('../locales/de/property_management.json').then((m) => m.default),
    purchasing: () => import('../locales/de/purchasing.json').then((m) => m.default),
    sales: () => import('../locales/de/sales.json').then((m) => m.default),
    scheduler: () => import('../locales/de/scheduler.json').then((m) => m.default),
    settings: () => import('../locales/de/settings.json').then((m) => m.default),
    staff: () => import('../locales/de/staff.json').then((m) => m.default),
    storage: () => import('../locales/de/storage.json').then((m) => m.default),
    superadmin: () => import('../locales/de/superadmin.json').then((m) => m.default),
    support: () => import('../locales/de/support.json').then((m) => m.default),
    template_gen: () => import('../locales/de/template_gen.json').then((m) => m.default),
    time_tracking: () => import('../locales/de/time_tracking.json').then((m) => m.default),
    vendors: () => import('../locales/de/vendors.json').then((m) => m.default),
  },
};

export async function loadNamespace(
  language: LanguageCode,
  namespace: TranslationNamespace,
): Promise<Record<string, unknown>> {
  const core = coreTranslations[language]?.[namespace];
  if (core) return core;
  const loader = lazyLoaders[language]?.[namespace];
  if (!loader) return {};
  try {
    return await loader();
  } catch (error) {
    console.warn(`[i18n] Failed to load ${language}/${namespace}`, error);
    return {};
  }
}

export async function loadNamespaces(
  language: LanguageCode,
  namespaces: TranslationNamespace[],
): Promise<Record<string, Record<string, unknown>>> {
  const out: Record<string, Record<string, unknown>> = {};
  await Promise.all(
    namespaces.map(async (ns) => {
      out[ns] = await loadNamespace(language, ns);
    }),
  );
  return out;
}

export { CORE_NAMESPACES, LAZY_NAMESPACES, ALL_NAMESPACES } from './generated-namespaces';
export type { TranslationNamespace } from './generated-namespaces';
